hilos_isabela/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('clientes/', include('clientes.urls', namespace='cliente')),
    path('productos/', include('productos.urls', namespace='producto')),
    path('marcas/', include('marcas.urls', namespace='marcas')),
    path('tipo_producto/', include('tipo_producto.urls', namespace='tipo_producto')),
]

marcas/urls.py
from django.urls import path

from .views import MarcaList, MarcaCreate, MarcaDetail, MarcaUpdate, MarcaDelete

app_name = 'marca'
urlpatterns = [
    path('', MarcaList.as_view(), name='marca-list'),
    path('detail/<int:pk>/', MarcaDetail.as_view(), name='detail'),
    path('create/', MarcaCreate.as_view(), name='create'),    
    path('update/<int:pk>/', MarcaUpdate.as_view(), name='update'),
    path('delete/<int:pk>/', MarcaDelete.as_view(), name='delete'),
]

productos/urls.py
from django.urls import path

from .views import ProductoList, ProductoDetail, ProductoCreate, ProductoUpdate, ProductoDelete

app_name = 'producto'
urlpatterns = [
    path('', ProductoList.as_view(), name='producto-list'),
    path('detail/<int:pk>/', ProductoDetail.as_view(), name='detail'),
    path('create/', ProductoCreate.as_view(), name='create'),
    path('update/<int:pk>/', ProductoUpdate.as_view(), name='update'),
    path('delete/<int:pk>/', ProductoDelete.as_view(), name='delete'),
]

productos/models.py
from django.db import models

from marcas.models import Marca
from tipo_producto.models import Tipo_producto

# Create your models here.

class Producto(models.Model):
    """tp = [
        ( 0 , 'Hilo'),
        ( 1 , 'Aguja'),
        ( 2 , 'Algodón'),
        ( 3 , 'Seda'),
        ( 4 , 'Cuero'),
        ( 5 , 'Poliéster'),
        ( 6 , 'Nylon')
    ]"""

    referencia = models.CharField(
        max_length=30, 
        unique=True, 
        help_text="Ingresar la referencia del producto")

    nombre = models.CharField(
        max_length=50, 
        help_text="Ingresar el nombre del producto")

    precio = models.IntegerField(
        help_text="Ingresar el precio del producto")

    cantidad = models.IntegerField(
        help_text="Ingresar la cantidad del producto")

    estado = models.BooleanField(
        "Habilitado", 
        default=True)

    marca = models.ForeignKey(
        Marca, 
        on_delete=models.CASCADE, 
        help_text="Ingrese la marca del producto")

    tipo_de_producto = models.ForeignKey(
        Tipo_producto, 
        on_delete=models.CASCADE, 
        help_text="Ingrese la tipo de producto del producto")

    """tipo_de_producto = models.SmallIntegerField(choices = tp, help_text="Ingresar el tipo del producto")"""
    

    def mostrar_estado(self):
        if self.estado:
            mostrar_estado = "Habilitado"
        else:
            mostrar_estado = "Inhabilitado"
        
        return mostrar_estado
    
    def __str__(self):
        return self.nombre

    class Meta:
        ordering = ('estado', 'precio', )
    

productos/forms.py
from django import forms
from django.forms import ModelForm
from .models import Producto

class ProductoForm(ModelForm):

	class Meta:
		model = Producto
		fields = '__all__'
		exclude = ('estado',)

	"""marca = forms.CharField(widget=forms.TextInput(attrs={
		'placeholder': 'Marca',
		'class': 'form-control',}))"""

	

productos/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from .models import Producto
from .forms import ProductoForm

class ProductoList(ListView):
	model = Producto
	template_name = 'productos/lista_producto.html'

class ProductoDetail(DetailView):
	model = Producto
	template_name = 'productos/detalle_producto.html'

class ProductoCreate(CreateView):
	model = Producto
	form_class = ProductoForm
	success_url = reverse_lazy('producto:producto-list')
	template_name = 'productos/create_update_producto.html'

class ProductoUpdate(UpdateView):
	model = Producto
	form_class = ProductoForm
	success_url = reverse_lazy('producto:producto-list')
	template_name = 'productos/create_update_producto.html'

class ProductoDelete(DeleteView):
	model = Producto
	success_url = reverse_lazy('producto:producto-list')
	template_name = 'productos/eliminar_producto.html'

templates/productos/create_update_producto.html
{% extends "clientes/base_cliente_lista.html" %}
{% block title %}Productos{% endblock title %}
{% block content %}
{% include "components/nav.html" %}
{% block producto %}
<div class="wrapper">
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Productos
      </h1>
      <ol class="breadcrumb">
        <li><a href=""><i class="fa fa-dashboard"></i>Inicio</a></li>
        <li><a href="{% url 'producto:producto-list' %}">productos</a></li>
        <li class="active">Nuevo producto</li>
      </ol>
    </section>
    <!-- Main content -->
    <section class="content">
      <!-- START ALERTS AND CALLOUTS -->
      <div class="row">
        <div class="col-md-12">
          <div class="box box-info">
            <div class="box-header with-border">

              <div class="box-tools pull-right">
                <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
              </div>

            </div>
            <div class="box-body">

              <div class="row">
                <div class="col-lg-12">
                  <form class="form-horizontal" method="post">
                    {% csrf_token %}
                    <div class="row">
                      <div class="col-xs-12 col-sm-10">
                        <div
                          class="form-group has-success has-feedback  {% if form.marca.errors %} has-error {% endif %}">
                          <label class="control-label col-sm-2" for="inputSuccess3">{{ form.marca.label_tag }}</label>
                          <div class="col-sm-6">
                            <select name="marca" class="form-control" placeholder="Marca" required id="id_marca">
                              {% for a in form.marca %}
                              {{a}}
                              {% endfor%}
                            </select>
                          </div>
                        </div>
                        <div
                          class="form-group has-success has-feedback  {% if form.tipo_de_producto.errors %} has-error {% endif %}">
                          <label class="control-label col-sm-2" for="inputSuccess3">{{ form.tipo_de_producto.label_tag }}</label>
                          <div class="col-sm-6">
                            <select name="tipo_de_producto" class="form-control" placeholder="tipo_de_producto" required id="id_tipo_de_producto">
                              {% for a in form.tipo_de_producto %}
                              {{a}}
                              {% endfor%}
                            </select>
                          </div>
                        </div>
                        <div
                          class="form-group has-success has-feedback  {% if form.referencia.errors %} has-error {% endif %}">
                          <label class="control-label col-sm-2"
                            for="inputSuccess3">{{ form.referencia.label_tag }}</label>
                          <div class="col-sm-6">
                            <input type="text" name="referencia" class="form-control"
                              value='{% if form.referencia.value %}{{ form.referencia.value }}{% endif %}'
                              data-toggle="tooltip" data-placement="top" title='{{ form.referencia.errors.as_text}}'
                              autofocus='true' id="disabledInput" type="text">
                          </div>
                        </div>
                        <div
                          class="form-group has-success has-feedback  {% if form.nombre.errors %} has-error {% endif %}">
                          <label class="control-label col-sm-2" for="inputSuccess3">{{ form.nombre.label_tag }}</label>
                          <div class="col-sm-6">
                            <input type="text" id="disabledTextInput" name="nombre" class="form-control"
                              value='{% if form.nombre.value %}{{ form.nombre.value }}{% endif %}' data-toggle="tooltip"
                              data-placement="top" title='{{ form.nombre.errors.as_text}}' autofocus='true'>
                          </div>
                        </div>
                        <div
                          class="form-group has-success has-feedback  {% if form.precio.errors %} has-error {% endif %}">
                          <label class="control-label col-sm-2" for="inputSuccess3">{{ form.precio.label_tag }}</label>
                          <div class="col-sm-6">
                            <input type="text" id="disabledTextInput" name="precio" class="form-control"
                              value='{% if form.precio.value %}{{ form.precio.value }}{% endif %}' data-toggle="tooltip"
                              data-placement="top" title='{{ form.precio.errors.as_text}}' autofocus='true'>
                          </div>
                        </div>
                        <div
                          class="form-group has-success has-feedback  {% if form.cantidad.errors %} has-error {% endif %}">
                          <label class="control-label col-sm-2"
                            for="inputSuccess3">{{ form.cantidad.label_tag }}</label>
                          <div class="col-sm-6">
                            <input type="text" id="disabledTextInput" name="cantidad" class="form-control"
                              value='{% if form.cantidad.value %}{{ form.cantidad.value }}{% endif %}'
                              data-toggle="tooltip" data-placement="top" title='{{ form.cantidad.errors.as_text}}'
                              autofocus='true'>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="panel-footer color-footer">
                      <button type="submit" class="btn btn-primary">
                        Guardar
                      </button>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
  {% endblock producto %}
  {% endblock content %}

templates/productos/detalle_producto.html
{% extends "clientes/base_cliente_lista.html" %}
{% block title %}productos{% endblock title %}
{% block content %}
{% include "components/nav.html" %}
{% block producto %}
<div class="wrapper">
	<!-- Content Wrapper. Contains page content -->
	<div class="content-wrapper">
		<!-- Main content -->
		<section class="content">
			<!-- START ALERTS AND CALLOUTS -->
			<div class="row">
				<div class="col-md-12">
					<div class="box box-info">

						<div class="box-header with-border">
							<a href="{% url 'producto:producto-list' %}" class="btn btn-success">
								<span class="glyphicon glyphicon-chevron-left"></span> Regresar
							</a>
							<div class="box-tools pull-right">
								<button class="btn btn-box-tool" data-widget="collapse"><i
										class="fa fa-minus"></i></button>
							</div>
						</div>
						<div class="box-body">
							<table class="table table-striped table table-hover ">
								<tbody>
									<tr class="success">
										<td><strong>Referencia:</strong></td>
										<td>{{ object.referencia }}</td>
									</tr>
									<tr class="success">
										<td><strong>Nombre:</strong></td>
										<td>{{ object.nombre }} </td>
									</tr>
									<tr class="success">
										<td><strong>Precio por unidad:</strong></td>
										<td>{{ object.precio }} </td>
									</tr>
									<tr class="success">
										<td><strong>Cantidad:</strong></td>
										<td>{{ object.cantidad }}</td>
									</tr>
									<tr class="success">
										<td><strong>Estado:</strong></td>
										<td>{{ object.mostrar_estado }}</td>
									</tr>
								</tbody>
							</table>
						</div>
					</div>
				</div>
		</section>
	</div>
	{% endblock producto %}
	{% endblock content %}

templates/productos/eliminar_producto.html
{% extends "clientes/base_cliente_lista.html" %}
{% block title %}Productos{% endblock title %}
{% block content %}
{% include "components/nav.html" %}
{% block producto %} 
<div class="wrapper"> 
      <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
        <!-- Main content -->
    <section class="content">          
      <!-- START ALERTS AND CALLOUTS -->     
      <div class="row">
        <div class="col-md-12">
          <div class="box box-info">
            <div class="box-header with-border">
              <i class="fa fa-bullhorn"></i>             
            </div>
              <div class="box-body">
                  <div class="callout callout-danger">                    
                    <h1>Eliminar</h1>
                    <form method="POST">
                    {% csrf_token %}
                      <p class="coloreliminar">¿Desea eliminar al producto "{{ object.nombre }}"?</p>
                      <input type="submit" value="Sí" class="btn btn-warning"> 
                      <a href="{% url 'producto:producto-list' %}" class="btn btn-info">No</a>
                    </form>                        
                  </div>                                   
              </div>
          </div>
        </div>
    </section>
  </div>   
{% endblock producto %}
{% endblock content %}

templates/productos/lista_producto.html
{% extends "clientes/base_cliente_lista.html" %}
{% block title %}Productos{% endblock title %}
{% block content %}
{% include "components/nav.html" %}
{% block producto %}
<div class="wrapper">
  <div class="content-wrapper">
    <section class="content-header">
      <h1>
        Productos
      </h1>
      <ol class="breadcrumb">
        <li><a href=""><i class="fa fa-dashboard"></i>Inicio</a></li>
        <li class="active">Productos</li>
        <li><a href="{% url 'producto:create' %}">Nuevo producto</a></li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">
          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title"><a href="{% url 'producto:create' %}" class="btn btn-success">
                  Nuevo producto
                </a></h3>
              <div class="box-tools pull-right">
                <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
              </div>
            </div>
            <div class="box-body">
              <table id="example1"  class="table table-bordered table-striped">
                <thead>
                  <tr>
                    <th>N°</th>
                    <th>Referencia</th>
                    <th>Nombre</th>
                    <th>Precio</th>
                    <th>Cantidad</th>
                    <th>Estado</th>
                    <th>Acciones</th>
                  </tr>
                </thead>
                <tbody>
                  {% for productos in object_list %}
                  <tr>
                    <td>{{ forloop.counter}}</td>
                    <td>{{ productos.referencia }}</td>
                    <td>{{ productos.nombre }} </td>
                    <td>{{ productos.precio}}</td>
                    <td>{{ productos.cantidad}}</td>
                    <td>{{ productos.mostrar_estado}}</td>
                    <td class="text-right">
                      <a href="{% url 'producto:detail' productos.id %}" class="btn btn-success"><span class="glyphicon glyphicon-eye-open"></span></a>
                      <a href="{% url 'producto:update' productos.id %}" class="btn btn-warning"><span class="glyphicon glyphicon-pencil"></span></a>
                      <a href="{% url 'producto:delete' productos.id %}" class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span></a>
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>

    {% endblock producto %}
    {% endblock content %}