hilos_isabela/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('clientes/', include('clientes.urls', namespace='cliente')),
    path('productos/', include('productos.urls', namespace='producto')),
    path('marcas/', include('marcas.urls', namespace='marcas')),
    path('tipo_producto/', include('tipo_producto.urls', namespace='tipo_producto')),
]

marcas/urls.py
from django.urls import path

from .views import MarcaList, MarcaCreate, MarcaDetail, MarcaUpdate, MarcaDelete

app_name = 'marca'
urlpatterns = [
    path('', MarcaList.as_view(), name='marca-list'),
    path('detail/<int:pk>/', MarcaDetail.as_view(), name='detail'),
    path('create/', MarcaCreate.as_view(), name='create'),    
    path('update/<int:pk>/', MarcaUpdate.as_view(), name='update'),
    path('delete/<int:pk>/', MarcaDelete.as_view(), name='delete'),
]

tipo_producto/urls.py
from django.urls import path

from .views import TipoProductoList, TipoProductoCreate, TipoProductoDetail, TipoProductoUpdate, TipoProductoDelete

app_name = 'tipo_producto'
urlpatterns = [
    path('', TipoProductoList.as_view(), name='tipo_producto-list'),    
    path('detail/<int:pk>/', TipoProductoDetail.as_view(), name='detail'),
    path('create/', TipoProductoCreate.as_view(), name='create'),
    path('update/<int:pk>/', TipoProductoUpdate.as_view(), name='update'),
    path('delete/<int:pk>/', TipoProductoDelete.as_view(), name='delete'),
]

templates/tipos_productos/create_update_tipo_producto.html
{% extends "clientes/base_cliente_lista.html" %}
{% block title %}Tipos de producto{% endblock title %}
{% block content %}
{% include "components/nav.html" %}
{% block tipo_producto %}
<div class="wrapper">
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Crear un nuevo tipo de producto
      </h1>
      <ol class="breadcrumb">
        <li><a href=""><i class="fa fa-dashboard"></i>Inicio</a></li>
        <li><a href="{% url 'tipo_producto:tipo_producto-list' %}">Tipos de producto</a></li>
        <li class="active">Nuevo tipo de producto</li>
      </ol>
    </section>
    <!-- Main content -->
    <section class="content">
      <!-- START ALERTS AND CALLOUTS -->
      <div class="row">
        <div class="col-md-12">
          <div class="box box-info">
            <div class="box-header with-border">

              <div class="box-tools pull-right">
                <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
              </div>

            </div>
            <div class="box-body">

              <div class="row">
                <div class="col-lg-12">
                  <form class="form-horizontal" method="post">
                    {% csrf_token %}
                    <div class="row">
                      <div class="col-xs-12 col-sm-10">
                        <div
                          class="form-group has-success has-feedback  {% if form.nombre.errors %} has-error {% endif %}">
                          <label class="control-label col-sm-2"
                            for="inputSuccess3">{{ form.nombre.label_tag }}</label>
                          <div class="col-sm-6">
                            <input type="text" name="nombre" class="form-control"
                              value='{% if form.nombre.value %}{{ form.nombre.value }}{% endif %}'
                              data-toggle="tooltip" data-placement="top"
                              title='{{ form.nombre.errors.as_text}}' autofocus='true' id="disabledInput"
                              type="text">
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="panel-footer color-footer">
                      <button type="submit" class="btn btn-primary">
                        Guardar
                      </button>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
  
  {% endblock tipo_producto %}
  {% endblock content %}

templates/tipos_productos/detalle_tipo_producto.html
{% extends "clientes/base_cliente_lista.html" %}
{% block title %}Tipos de producto{% endblock title %}
{% block content %}
{% include "components/nav.html" %}
{% block tipo_producto %}
<div class="wrapper">
	<!-- Content Wrapper. Contains page content -->
	<div class="content-wrapper">
		<!-- Main content -->
		<section class="content">
			<!-- START ALERTS AND CALLOUTS -->
			<div class="row">
				<div class="col-md-12">
					<div class="box box-info">

						<div class="box-header with-border">
							<a href="{% url 'tipo_producto:tipo_producto-list' %}" class="btn btn-success">
								<span class="glyphicon glyphicon-chevron-left"></span> Regresar
							</a>
							<div class="box-tools pull-right">
								<button class="btn btn-box-tool" data-widget="collapse"><i
										class="fa fa-minus"></i></button>
							</div>
						</div>
						<div class="box-body">
							<table class="table table-striped table table-hover ">
								<tbody>
									<tr class="success">
										<td><strong>Nombre:</strong></td>
										<td>{{ object.nombre }}</td>
									</tr>									
								</tbody>
							</table>
						</div>
					</div>
				</div>
		</section>
	</div>
	{% endblock tipo_producto %}
	{% endblock content %}

templates/tipos_productos/eliminar_tipo_producto.html
{% extends "clientes/base_cliente_lista.html" %}
{% block title %}Tipos de producto{% endblock title %}
{% block content %}
{% include "components/nav.html" %}
{% block tipo_producto %} 
<div class="wrapper"> 
      <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
        <!-- Main content -->
    <section class="content">          
      <!-- START ALERTS AND CALLOUTS -->     
      <div class="row">
        <div class="col-md-12">
          <div class="box box-info">
            <div class="box-header with-border">
              <i class="fa fa-bullhorn"></i>             
            </div>
              <div class="box-body">
                  <div class="callout callout-danger">                    
                    <h1> Eliminar</h1>
                    <form method="POST">
                    {% csrf_token %}
                      <p class="coloreliminar">¿Desea eliminar la tipo_producto: {{ object.nombre }}?</p>
                      <input type="submit" value="Sí" class="btn btn-warning"> 
                      <a href="{% url 'tipo_producto:tipo_producto-list' %}" class="btn btn-info">No</a>
                    </form>                        
                  </div>                                   
              </div>
          </div>
        </div>
    </section>
  </div>   
{% endblock tipo_producto %}
{% endblock content %}

templates/tipos_productos/lista_tipo_producto.html
{% extends "clientes/base_cliente_lista.html" %}
{% block title %}Tipos de producto{% endblock title %}
{% block content %}
{% include "components/nav.html" %}
{% block tipo_producto %}
<div class="wrapper">
  <div class="content-wrapper">
    <section class="content-header">
      <h1>
        Tipos de producto
      </h1>
      <ol class="breadcrumb">
        <li><a href=""><i class="fa fa-dashboard"></i>Inicio</a></li>
        <li class="active">Tipos de procduto</li>
        <li><a href="{% url 'tipo_producto:create' %}">Nuevo tipo de producto</a></li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">
          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title"><a href="{% url 'tipo_producto:create' %}" class="btn btn-success">
                  Nuevo tipo de producto
                </a></h3>
              <div class="box-tools pull-right">
                <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
              </div>
            </div>
            <div class="box-body">
              <table id="example1"  class="table table-bordered table-striped">
                <thead>
                  <tr>
                    <th>N°</th>
                    <th>Nombre</th>
                  </tr>
                </thead>
                <tbody>
                  {% for tipo_producto in object_list %}
                  <tr>
                    <td>{{ forloop.counter}}</td>
                    <td>{{ tipo_producto.nombre }} </td>
                    <td class="text-right">
                      <a href="{% url 'tipo_producto:detail' tipo_producto.id %}" class="btn btn-success"><span class="glyphicon glyphicon-eye-open"></span></a>
                      <a href="{% url 'tipo_producto:update' tipo_producto.id %}" class="btn btn-warning"><span class="glyphicon glyphicon-pencil"></span></a>
                      <a href="{% url 'tipo_producto:delete' tipo_producto.id %}" class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span></a>
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>

    {% endblock tipo_producto %}
    {% endblock content %}