clientes/urls.py
from django.urls import path

from .views import ClienteList, ClienteCreate, ClienteUpdate, ClienteDetail, ClienteDelete

app_name = 'cliente'
urlpatterns = [
    path('', ClienteList.as_view(), name='cliente-list'),
    path('detail/<int:pk>/', ClienteDetail.as_view(), name='detail'),
    path('create/', ClienteCreate.as_view(), name='create'),
    path('update/<int:pk>/', ClienteUpdate.as_view(), name='update'),
    path('delete/<int:pk>/', ClienteDelete.as_view(), name='delete'),
]

hilos_isabela/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('clientes/', include('clientes.urls', namespace='cliente')),
    path('productos/', include('productos.urls', namespace='producto')),
    path('marcas/', include('marcas.urls', namespace='marcas')),
    path('tipo_producto/', include('tipo_producto.urls', namespace='tipo_producto')),
]

marcas/urls.py
from django.urls import path

from .views import MarcaList, MarcaCreate, MarcaDetail, MarcaUpdate, MarcaDelete

app_name = 'marca'
urlpatterns = [
    path('', MarcaList.as_view(), name='marca-list'),
    path('detail/<int:pk>/', MarcaDetail.as_view(), name='detail'),
    path('create/', MarcaCreate.as_view(), name='create'),    
    path('update/<int:pk>/', MarcaUpdate.as_view(), name='update'),
    path('delete/<int:pk>/', MarcaDelete.as_view(), name='delete'),
]

productos/urls.py
from django.urls import path

from .views import ProductoList, ProductoDetail, ProductoCreate, ProductoUpdate, ProductoDelete

app_name = 'producto'
urlpatterns = [
    path('', ProductoList.as_view(), name='producto-list'),
    path('detail/<int:pk>/', ProductoDetail.as_view(), name='detail'),
    path('create/', ProductoCreate.as_view(), name='create'),
    path('update/<int:pk>/', ProductoUpdate.as_view(), name='update'),
    path('delete/<int:pk>/', ProductoDelete.as_view(), name='delete'),
]

templates/components/nav.html
<div class="wrapper">
      <header class="main-header">
        <!-- Logo -->
        <a href="#" class="logo">
          <!-- mini logo for sidebar mini 50x50 pixels -->
          <span class="logo-mini"><b>H</b>I</span>
          <!-- logo for regular state and mobile devices -->
          <span class="logo-lg"><b>Hilos</b>Isabela</span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top" role="navigation">
        </nav>
      </header>
      <!-- Left side column. contains the logo and sidebar -->
      <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
          <!-- Sidebar user panel -->
          <div class="user-panel">
              <div class="pull-left image">
                <br><br><br>
                  </div>
            <div class="pull-left info">
              <p>{{ user.username|capfirst }}</p>
              <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
          </div>

          <ul class="sidebar-menu">
            <li class="header">NAVEGACIÓN PRINCIPAL</li>
            <li class="treeview">
              <a href="#">
                <i class="fa fa-child"></i> <span>Clientes</span> <i class="fa fa-angle-left pull-right"></i>
              </a>
              <ul class="treeview-menu">
                <li class="active"><a href="{% url 'cliente:cliente-list' %}"><i class="fa fa-check-square"></i> Lista</a></li>
                <li><a href="{% url 'cliente:create' %}"><i class="fa fa-save"></i><small class="label pull-right bg-green">Nuevo</small>Nuevo</a></li>
              </ul>
            </li>

            <li class="treeview">
              <a href="#">
                <i class="fa fa-archive"></i> <span>Productos</span> <i class="fa fa-angle-left pull-right"></i>
              </a>
              <ul class="treeview-menu">
                <li class="active"><a href="{% url 'producto:producto-list' %}"><i class="fa fa-check-square"></i> Lista</a></li>
                <li><a href="{% url 'producto:create' %}"><i class="fa fa-save"></i><small class="label pull-right bg-green">Nuevo</small>Nuevo</a></li>
              </ul>
            </li>

            <li class="treeview">
                <a href="#">
                  <i class="fa fa-archive"></i> <span>Marcas</span> <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                  <li class="active"><a href="{% url 'marca:marca-list' %}"><i class="fa fa-check-square"></i> Lista</a></li>
                  <li><a href="{% url 'marca:create' %}"><i class="fa fa-save"></i><small class="label pull-right bg-green">Nueva</small>Nueva</a></li>
                </ul>
              </li>
            <!--<li class="treeview">
              <a href="#">
                <i class="fa fa-child"></i> <span>Laboratorios</span> <i class="fa fa-angle-left pull-right"></i>
              </a>
              <ul class="treeview-menu">
                <li class="active"><a href=""><i class="fa fa-check-square"></i> Lista</a></li>
                <li><a href=""><i class="fa fa-save"></i><small class="label pull-right bg-green">Nuevo</small>Nuevo</a></li>
              </ul>
            </li>

            <li class="treeview">
              <a href="#">
                <i class="fa fa-medkit"></i>
                <span>Medicamentos</span>
                <span class="label label-primary pull-right">2</span>
              </a>
              <ul class="treeview-menu">
                <li><a href=""><i class="fa fa fa-check-square"></i> Lista</a></li>                
                <li><a href=""><i class="fa fa-save"></i><small class="label pull-right bg-green">Nuevo</small>Nuevo</a></li>               
              </ul>
            </li>

     
            <li class="treeview">
              <a href="#">
                <i class="fa fa-pie-chart"></i>
                <span>Compras</span>
                <i class="fa fa-angle-left pull-right"></i>
              </a>
              <ul class="treeview-menu">
                <li><a href=""><i class="fa fa-circle-o"></i> Listado de Compras</a></li>
                <li><a href=""><i class="fa fa-circle-o"></i> Realizar Compras</a></li>
                <li><a href=""><i class="fa fa-circle-o"></i> Reportes Compras</a></li>                
              </ul>
            </li>
            -->
            <li class="treeview">
              <a href="#">
                <i class="fa fa-laptop"></i>
                <span>Ventas</span>
                <i class="fa fa-angle-left pull-right"></i>
              </a>
              <ul class="treeview-menu">
              <li><a href=""><i class="fa fa-circle-o"></i> Lista Ventas</a></li>
               
                <li><a href=""><i class="fa fa-circle-o"></i> Realizar Venta</a></li>
                <li><a href=""><i class="fa fa-circle-o"></i> Consultar Venta</a></li>
                <li><a href=""><i class="fa fa-circle-o"></i> Reporte Venta</a></li>
               
              </ul>
            </li>
        </section>
      </aside>
      