clientes/urls.py
from django.urls import path

from .views import ClienteList, ClienteCreate, ClienteUpdate, ClienteDetail, ClienteDelete

app_name = 'cliente'
urlpatterns = [
    path('', ClienteList.as_view(), name='cliente-list'),
    path('detail/<int:pk>/', ClienteDetail.as_view(), name='detail'),
    path('create/', ClienteCreate.as_view(), name='create'),
    path('update/<int:pk>/', ClienteUpdate.as_view(), name='update'),
    path('delete/<int:pk>/', ClienteDelete.as_view(), name='delete'),
]

hilos_isabela/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('clientes/', include('clientes.urls', namespace='cliente')),
    path('productos/', include('productos.urls', namespace='producto')),
    path('marcas/', include('marcas.urls', namespace='marcas')),
    path('tipo_producto/', include('tipo_producto.urls', namespace='tipo_producto')),
]

marcas/urls.py
from django.urls import path

from .views import MarcaList, MarcaCreate, MarcaDetail, MarcaUpdate, MarcaDelete

app_name = 'marca'
urlpatterns = [
    path('', MarcaList.as_view(), name='marca-list'),
    path('detail/<int:pk>/', MarcaDetail.as_view(), name='detail'),
    path('create/', MarcaCreate.as_view(), name='create'),    
    path('update/<int:pk>/', MarcaUpdate.as_view(), name='update'),
    path('delete/<int:pk>/', MarcaDelete.as_view(), name='delete'),
]

clientes/models.py
from django.db import models

from .validators import validate_only_letters

class Cliente(models.Model):

    """tipo_cl = [
        ( 0 , 'Independiente'),
        ( 1 , 'Empresa'),
        ( 2 , 'Local')
    ]"""

    """tipo_de_cliente= models.SmallIntegerField(
		choices=tipo_cl, 
		help_text="Ingrese el tipo del cliente"
	)"""

    """tipo_de_documento = models.SmallIntegerField(
		choices=tipo_id, 
		help_text="Ingresar el tipo de documento de identidad"
	)"""

    documento_identidad = models.IntegerField(
        unique=True,
        help_text="Ingresar solo números")

    primer_nombre = models.CharField(
        max_length=40,
        validators=[validate_only_letters],
        help_text="Ingresar solo letras")

    segundo_nombre = models.CharField(
        max_length=40, blank=True,
        validators=[validate_only_letters],
        null=True,
        help_text="Ingresar solo letras")

    primer_apellido = models.CharField(
        validators=[validate_only_letters],
        max_length=40,
        help_text="Ingresar solo letras")

    segundo_apellido = models.CharField(
        max_length=40,
        validators=[validate_only_letters],
        help_text="Ingresar solo letras")
    
    correo_electronico = models.EmailField(
		max_length=100, 
		null=True, 
		blank=True, 
		unique=True, 
		help_text="Ingresa un dirección de correo valida")

    direccion = models.CharField(
        max_length=35,
        help_text="Ingresar una dirección valida")

    telefono = models.IntegerField(
        help_text="Ingresar solo números")

    def nombre_completo(self):
        if self.segundo_nombre:
            nombre = "{0} {1} {2} {3}".format(
                self.primer_nombre,
                self.segundo_nombre,
                self.primer_apellido,
                self.segundo_apellido)
        else:
            nombre = "{0} {1} {2}".format(
                self.primer_nombre,
                self.primer_apellido,
                self.segundo_apellido)
        return nombre


    def __str__(self):
        return self.nombre_completo()

clientes/forms.py
from django import forms
from django.forms import ModelForm
from django.core.exceptions import ValidationError

from .models import Cliente

class ClienteForm(ModelForm):
    class Meta:
        model = Cliente
        fields = '__all__'

    fields_only_letters = [
        'primer_nombre', 'segundo_nombre', 
        'primer_apellido', 'segundo_apellido'
    ]

    documento_identidad = forms.CharField(widget=forms.NumberInput(attrs={
        'placeholder': 'DNI',
        'size': '8'}))
    primer_nombre = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Nombre Cliente',
        'size': '40',
        'pattern': "[-a-zA-Z_]+"}))	
    primer_apellido = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Apellidos',
        'size': '40'}))		
    direccion = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Direccion',
        'size': '40'}))	
    telefono = forms.CharField(widget=forms.NumberInput(attrs={
        'placeholder': 'Telefono',
        'size': '8'}))

    """def clean_documento_identidad(self):
        diccionario_limpio = self.cleaned_data
        documento_identidad = diccionario_limpio.get('documento_identidad')
        if len(documento_identidad) < 8 or len(documento_identidad) > 8:
            raise forms.ValidationError("debe ser de 8 Digitos")
        return documento_identidad"""

    def nombre(self):
        primer_nombre = self.cleaned_data['primer_nombre']
        if not primer_nombre.isalpha():
            raise forms.ValidationError('No puede contener números')
        return primer_nombre

    """def __init__(self, *args, **kwargs):
        super(ClienteForm, self).__init__(*args, **kwargs)

        for visible in self.visible_fields():
            attrs = {'class': 'form-control', 'placeholder': visible.label}
            if visible.name in self.fields_only_letters:
                attrs.update({'pattern': "[-a-zA-Z_]+"})

            visible.field.widget.attrs.update(attrs)

            if self.errors.get(visible.name, None):
                visible.field.widget.attrs.update({'class': 'form-control is-invalid'})"""

clientes/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from .models import Cliente
from .forms import ClienteForm

class ClienteList(ListView):
	model = Cliente
	template_name = 'clientes/lista_cliente.html'

class ClienteDetail(DetailView):
	model = Cliente
	template_name = 'clientes/detalle_clientes.html'

class ClienteCreate(CreateView):
	model = Cliente
	form_class = ClienteForm
	success_url = reverse_lazy('cliente:cliente-list')
	template_name = 'clientes/create_update_clientes.html'

class ClienteUpdate(UpdateView):
	model = Cliente
	form_class = ClienteForm
	success_url = reverse_lazy('cliente:cliente-list')
	template_name = 'clientes/create_update_clientes.html'

class ClienteDelete(DeleteView):
	model = Cliente
	success_url = reverse_lazy('cliente:cliente-list')
	template_name = 'clientes/eliminar_cliente.html'

templates/clientes/base_cliente_lista.html
{% extends "base.html" %}
{% load staticfiles %}
{% block css %}

   <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.5 -->
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- DataTables -->
    <link rel="stylesheet" href="/static/plugins/datatables/dataTables.bootstrap.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/static/dist/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="/static/dist/css/skins/_all-skins.min.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
{% endblock css %}
{% block js %}
    <!-- jQuery 2.1.4 -->
    <script src="/static/plugins/jQuery/jQuery-2.1.4.min.js"></script>
    <!-- Bootstrap 3.3.5 -->
    <script src="/static/bootstrap/js/bootstrap.min.js"></script>
    <!-- DataTables -->
    <script src="/static/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="/static/plugins/datatables/dataTables.bootstrap.min.js"></script>
    <!-- SlimScroll -->
    <script src="/static/plugins/slimScroll/jquery.slimscroll.min.js"></script>
    <!-- FastClick -->
    <script src="/static/plugins/fastclick/fastclick.min.js"></script>
    <!-- AdminLTE App -->
    <script src="/static/dist/js/app.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="/static/dist/js/demo.js"></script>
    <!-- page script -->
    <script>
      $(function () {
        $("#example1").DataTable();
        $('#example2').DataTable({
          "paging": true,
          "lengthChange": false,
          "searching": false,
          "ordering": true,
          "info": true,
          "autoWidth": false
        });
      });
    </script>
{% endblock js %}

templates/clientes/create_update_clientes.html
{% extends "clientes/base_cliente_lista.html" %}
{% block title %}Clientes{% endblock title %}
{% block content %}
{% include "components/nav.html" %}
{% block producto %}
<div class="wrapper">
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Clientes
      </h1>
      <ol class="breadcrumb">
        <li><a href=""><i class="fa fa-dashboard"></i>Inicio</a></li>
        <li><a href="{% url 'cliente:cliente-list' %}">Clientes</a></li>
        <li class="active">Nuevo Cliente</li>
      </ol>
    </section>
    <!-- Main content -->
    <section class="content">
      <!-- START ALERTS AND CALLOUTS -->
      <div class="row">
        <div class="col-md-12">
          <div class="box box-info">
            <div class="box-header with-border">

              <div class="box-tools pull-right">
                <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
              </div>

            </div>
            <div class="box-body">

              <div class="row">
                <div class="col-lg-12">
                  <form class="form-horizontal" method="post">
                    {% csrf_token %}
                    <div class="row">
                      <div class="col-xs-12 col-sm-10">
                        <div
                          class="form-group has-success has-feedback  {% if form.documento_identidad.errors %} has-error {% endif %}">
                          <label class="control-label col-sm-2"
                            for="inputSuccess3">{{ form.documento_identidad.label_tag }}</label>
                          <div class="col-sm-6">
                            <input type="text" name="documento_identidad" class="form-control"
                              value='{% if form.documento_identidad.value %}{{ form.documento_identidad.value }}{% endif %}'
                              data-toggle="tooltip" data-placement="top"
                              title='{{ form.documento_identidad.errors.as_text}}' autofocus='true' id="disabledInput"
                              type="text">
                          </div>
                        </div>
                        <div
                          class="form-group has-success has-feedback  {% if form.primer_nombre.errors %} has-error {% endif %}">
                          <label class="control-label col-sm-2" for="inputSuccess3">{{ form.primer_nombre.label_tag }}</label>
                          <div class="col-sm-6">
                            <input type="text" id="disabledTextInput" name="primer_nombre" class="form-control"
                              value='{% if form.primer_nombre.value %}{{ form.primer_nombre.value }}{% endif %}' data-toggle="tooltip"
                              data-placement="top" title='{{ form.primer_nombre.errors.as_text}}' autofocus='true'>
                          </div>
                        </div>
                        <div
                          class="form-group has-success has-feedback  {% if form.segundo_nombre.errors %} has-error {% endif %}">
                          <label class="control-label col-sm-2" for="inputSuccess3">{{ form.segundo_nombre.label_tag }}</label>
                          <div class="col-sm-6">
                            <input type="text" id="disabledTextInput" name="segundo_nombre" class="form-control"
                              value='{% if form.segundo_nombre.value %}{{ form.segundo_nombre.value }}{% endif %}' data-toggle="tooltip"
                              data-placement="top" title='{{ form.segundo_nombre.errors.as_text}}' autofocus='true'>
                          </div>
                        </div>
                        <div
                          class="form-group has-success has-feedback  {% if form.primer_apellido.errors %} has-error {% endif %}">
                          <label class="control-label col-sm-2"
                            for="inputSuccess3">{{ form.primer_apellido.label_tag }}</label>
                          <div class="col-sm-6">
                            <input type="text" id="disabledTextInput" name="primer_apellido" class="form-control"
                              value='{% if form.primer_apellido.value %}{{ form.primer_apellido.value }}{% endif %}'
                              data-toggle="tooltip" data-placement="top" title='{{ form.primer_apellido.errors.as_text}}'
                              autofocus='true'>
                          </div>
                        </div>
                        <div
                          class="form-group has-success has-feedback  {% if form.segundo_apellido.errors %} has-error {% endif %}">
                          <label class="control-label col-sm-2"
                            for="inputSuccess3">{{ form.segundo_apellido.label_tag }}</label>
                          <div class="col-sm-6">
                            <input type="text" id="disabledTextInput" name="segundo_apellido" class="form-control"
                              value='{% if form.segundo_apellido.value %}{{ form.segundo_apellido.value }}{% endif %}'
                              data-toggle="tooltip" data-placement="top" title='{{ form.segundo_apellido.errors.as_text}}'
                              autofocus='true'>
                          </div>
                        </div>
                        <div
                          class="form-group has-success has-feedback  {% if form.correo_electronico.errors %} has-error {% endif %}">
                          <label class="control-label col-sm-2"
                            for="inputSuccess3">{{ form.correo_electronico.label_tag }}</label>
                          <div class="col-sm-6">
                            <input type="text" id="disabledTextInput" name="correo_electronico" class="form-control"
                              value='{% if form.correo_electronico.value %}{{ form.correo_electronico.value }}{% endif %}'
                              data-toggle="tooltip" data-placement="top" title='{{ form.correo_electronico.errors.as_text}}'
                              autofocus='true'>
                          </div>
                        </div>
                        <div
                          class="form-group has-success has-feedback  {% if form.direccion.errors %} has-error {% endif %}">
                          <label class="control-label col-sm-2"
                            for="inputSuccess3">{{ form.direccion.label_tag }}</label>
                          <div class="col-sm-6">
                            <input type="text" id="disabledTextInput" name="direccion" class="form-control"
                              value='{% if form.direccion.value %}{{ form.direccion.value }}{% endif %}'
                              data-toggle="tooltip" data-placement="top" title='{{ form.direccion.errors.as_text}}'
                              autofocus='true'>
                          </div>
                        </div>
                        <div
                          class="form-group has-success has-feedback  {% if form.telefono.errors %} has-error {% endif %}">
                          <label class="control-label col-sm-2"
                            for="inputSuccess3">{{ form.telefono.label_tag }}</label>
                          <div class="col-sm-6">
                            <input type="number" id="disabledTextInput" name="telefono" class="form-control"
                              value='{% if form.telefono.value %}{{ form.telefono.value }}{% endif %}'
                              data-toggle="tooltip" data-placement="top" title='{{ form.telefono.errors.as_text}}'
                              autofocus='true'>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="panel-footer color-footer">
                      <button type="submit" class="btn btn-primary">
                        Guardar
                      </button>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
  
  {% endblock producto %}
  {% endblock content %}

templates/clientes/detalle_clientes.html
{% extends "clientes/base_cliente_lista.html" %}
{% block title %}Clientes{% endblock title %}
{% block content %}
{% include "components/nav.html" %}
{% block producto %}
<div class="wrapper">
	<!-- Content Wrapper. Contains page content -->
	<div class="content-wrapper">
		<!-- Main content -->
		<section class="content">
			<!-- START ALERTS AND CALLOUTS -->
			<div class="row">
				<div class="col-md-12">
					<div class="box box-info">

						<div class="box-header with-border">
							<a href="{% url 'cliente:cliente-list' %}" class="btn btn-success">
								<span class="glyphicon glyphicon-chevron-left"></span> Regresar
							</a>
							<div class="box-tools pull-right">
								<button class="btn btn-box-tool" data-widget="collapse"><i
										class="fa fa-minus"></i></button>
							</div>
						</div>
						<div class="box-body">
							<table class="table table-striped table table-hover ">
								<tbody>
									<tr class="success">
										<td><strong>Documento de identidad:</strong></td>
										<td>{{ object.documento_identidad }}</td>
									</tr>
									<tr class="success">
										<td><strong>Primer nombre:</strong></td>
										<td>{{ object.primer_nombre }} </td>
									</tr>
									<tr class="success">
										<td><strong>Segundo nombre:</strong></td>
										<td>{{ object.segundo_nombre }} </td>
									</tr>
									<tr class="success">
										<td><strong>Primer apellido:</strong></td>
										<td>{{ object.primer_apellido }}</td>
									</tr>
									<tr class="success">
										<td><strong>Segundo apellido:</strong></td>
										<td>{{ object.segundo_apellido }}</td>
									</tr>
									<tr class="success">
										<td><strong>Correo electrónico:</strong></td>
										<td>{{ object.correo_electronico }}</td>
									</tr>

									<tr class="success">
										<td><strong>Dirección:</strong></td>
										<td>{{ object.direccion }}</td>
									</tr>
									<tr class="success">
										<td><strong>Teléfono:</strong> </td>
										<td>{{ object.telefono}}</td>
									</tr>
								</tbody>
							</table>
						</div>
					</div>
				</div>
		</section>
	</div>
	{% endblock producto %}
	{% endblock content %}

templates/clientes/eliminar_cliente.html
{% extends "clientes/base_cliente_lista.html" %}
{% block title %}Clientes{% endblock title %}
{% block content %}
{% include "components/nav.html" %}
{% block producto %} 
<div class="wrapper"> 
      <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
        <!-- Main content -->
    <section class="content">          
      <!-- START ALERTS AND CALLOUTS -->     
      <div class="row">
        <div class="col-md-12">
          <div class="box box-info">
            <div class="box-header with-border">
              <i class="fa fa-bullhorn"></i>             
            </div>
              <div class="box-body">
                  <div class="callout callout-danger">                    
                    <h1> Eliminar</h1>
                    <form method="POST">
                    {% csrf_token %}
                      <p class="coloreliminar">¿Desea eliminar al cliente "{{ object.nombre_completo }}?</p>
                      <input type="submit" value="Sí" class="btn btn-warning"> 
                      <a href="{% url 'cliente:cliente-list' %}" class="btn btn-info">No</a>
                    </form>                        
                  </div>                                   
              </div>
          </div>
        </div>
    </section>
  </div>   
{% endblock producto %}
{% endblock content %}

templates/clientes/lista_cliente.html
{% extends "clientes/base_cliente_lista.html" %}
{% block title %}Clientes{% endblock title %}
{% block content %}
{% include "components/nav.html" %}
{% block producto %}
<div class="wrapper">
  <div class="content-wrapper">
    <section class="content-header">
      <h1>
        Clientes
      </h1>
      <ol class="breadcrumb">
        <li><a href=""><i class="fa fa-dashboard"></i>Inicio</a></li>
        <li class="active">Clientes</li>
        <li><a href="{% url 'cliente:create' %}">Nuevo Cliente</a></li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">
          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title"><a href="{% url 'cliente:create' %}" class="btn btn-success">
                  Nuevo Cliente
                </a></h3>
              <div class="box-tools pull-right">
                <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
              </div>
            </div>
            <div class="box-body">
              <table id="example1"  class="table table-bordered table-striped">
                <thead>
                  <tr>
                    <th>N°</th>
                    <th>Documento de identidad</th>
                    <th>Nombre completo</th>
                    <th>Teléfono</th>
                    <th>Acciones</th>
                  </tr>
                </thead>
                <tbody>
                  {% for clientes in object_list %}
                  <tr>
                    <td>{{ forloop.counter}}</td>
                    <td>{{ clientes.documento_identidad }}</td>
                    <td>{{ clientes.nombre_completo }} </td>
                    <td>{{ clientes.telefono}}</td>
                    <td class="text-right">
                      <a href="{% url 'cliente:detail' clientes.id %}" class="btn btn-success"><span class="glyphicon glyphicon-eye-open"></span></a>
                      <a href="{% url 'cliente:update' clientes.id %}" class="btn btn-warning"><span class="glyphicon glyphicon-pencil"></span></a>
                      <a href="{% url 'cliente:delete' clientes.id %}" class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span></a>
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>

    {% endblock producto %}
    {% endblock content %}